### ISSUE TITLE
Where is .configure/nvim/.init.vim ?

### ISSUE THREAD

**Issue by nguxx** [neovim/neovim-snap#10]
Hi,
Sorry for this dumb question
I'm installing nvim on AWS Linux Ec2, I works fine., 
But I try to put my init.vim and some pluggins but I cannot find `.config`and `.local/share`
I have rep : `/snap/nvim` and `/var/snap/nvim` and `/var/lib/snapd/snap/nvim/` but I cannot spot `init.vim`
thanks

**Comment by hurricanehrndz** [comment]
Sorry I can’t help with this specific issues since it does no deal directly with the package. You can always make whichever directories you require.
