### ISSUE TITLE
Need more access to automate releases

### ISSUE THREAD

**Issue by hurricanehrndz** [neovim/neovim-snap#19]
I will like to start automating nightly and tagged releases. I require more access in this repo to set the appropriate secrets.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/snap-automated-build/3452/1

**Comment by justinmk** [comment]
@hurricanehrndz you are now Admin on this repo.
