### ISSUE TITLE
Where are the configuration files stored?

### ISSUE THREAD

**Issue by MarioBross69** [neovim/neovim-snap#20]
Hi, I have installed nvim snap from the Ubuntu 22.04 software store, but it does not read my configuration files that are in .config/nvim
I have copied them to ~snap/nvim/current/.config/nvim but it does not work either
Thanks

**Comment by MarioBross69** [comment]
My configuration files that are in .config/nvim
I see that the command to install from the command line is: sudo snap install nvim --classic
maybe when installing from Ubuntu Snap-store the --classic option is not being used

**Comment by MarioBross69** [comment]
Sorry..., the error was mine, I have verified that if it reads the configuration file in .config/nvim, whether it is installed from the command line or from Ubuntu snap-store
What the snap package did not read was the "main.shada", in the snap package it should go in .local/state/nvim while before it was in .local/share/nvim
Sorry and Thanks

**Comment by James4Ever0** [comment]
Type `:checkhealth` and you will know the real path of the config file.

In my case, if `nvim` is installed via `snap`, under `root` account the default config file path is `/home/root/.config/nvim/init.lua`.
