### ISSUE TITLE
Update to Neovim v0.9.0

### ISSUE THREAD

**Issue by Flimm** [neovim/neovim-snap#24]
Nvim v0.9.0 has been released: https://github.com/neovim/neovim/releases/tag/v0.9.0

Can the snap version of Neovim be updated to 0.9.0?

**Comment by rbrud** [comment]
An updated version of Neovim would make my day. Thanks in advance.

**Comment by hurricanehrndz** [comment]
Should have been updated already

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hurricanehrndz** [comment]
@rbrud I just triggered the new release, and open up an issue with neovim/neovim#23496

**Comment by hurricanehrndz** [comment]
![image](https://user-images.githubusercontent.com/5804237/236581335-3309d42b-1092-4563-a10c-4d9ec7639332.png)

**Comment by Flimm** [comment]
Thank you! The 0.9.0 version of `nvim` on snap has been released: https://snapcraft.io/nvim
