### ISSUE TITLE
Update to 0.9.4?

### ISSUE THREAD

**Issue by amardhruva** [neovim/neovim-snap#26]
Can we have the snap updated to 0.9.4?

**Comment by amardhruva** [comment]
I manually built both 0.9.1(current snap) and 0.9.4 and the following issue is fixed in 0.9.4
https://github.com/NvChad/NvChad/issues/2509#event-11030558088

**Comment by justinmk** [comment]
This repo is somewhat unmaintained currently. Are you interested in maintaining it?

**Comment by hurricanehrndz** [comment]
I just triggered the release.
