### ISSUE TITLE
Request to move the config and data folders to the snap specific folders

### ISSUE THREAD

**Issue by soumyaDghosh** [neovim/neovim-snap#27]
The snap neovim works great. But, it'd be awesome if we could have separate configs for the traditional and the snap package. To do that, we need to specify the `XDG_CONFIG_HOME` and `XDG_DATA_DIR`. We can also add a migrate helper. Thus, the current user will also not suffer.

**Comment by justinmk** [comment]
This repo is somewhat unmaintained currently. Are you interested in maintaining it?

**Comment by soumyaDghosh** [comment]
Sure, I can maintain it. We can also have the manifest maintained by the snapcrafters.

**Comment by justinmk** [comment]
> We can also have the manifest maintained by the snapcrafters.

Do we need to request that somewhere?

**Comment by soumyaDghosh** [comment]
Snapcrafters org has a lot of backlogs. I have also just joined the org., so, I am unsure if they'll accept. But, what I can do for now is, I individually maintain this package, with some access to this repo. I don't need any sensitive details, just one upstream dev to discuss whenever drastic changes are needed. Also, I can do a lot of automations here, which are used in the snapcrafters.

**Comment by hurricanehrndz** [comment]
I would happily review any PRs, ps all that is needed for automation is setting up a schedule for the jobs.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

The current action: https://github.com/neovim/neovim-snap/actions/runs/6445625277/job/17499890289

Will do the rest.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by justinmk** [comment]
> all that is needed for automation is setting up a schedule for the jobs.

Nice! Here's an example of how to do that: https://github.com/neovim/neovim-backup/blob/3aa74e1a017f62eac81d529f5d3e4da5039c4ad2/.github/workflows/backup.yml#L5-L6

**Comment by justinmk** [comment]
> it'd be awesome if we could have separate configs for the traditional and the snap package. To do that, we need to specify the `XDG_CONFIG_HOME` and `XDG_DATA_DIR`. We can also add a migrate helper.

You can easily do that using Nvim's `NVIM_APPNAME` feature. https://neovim.io/doc/user/starting.html#_nvim_appname
