### ISSUE TITLE
Update for 0.10.0?

### ISSUE THREAD

**Issue by josalvatorre** [neovim/neovim-snap#29]
Could we please release a snap for [Neovim 0.10.0][1]? I'm desperate for the improved clipboard support 😅

I understand that this is probably a more niche distribution with fewer users and that it's hard to maintain many distribution channels. I could be happy to just use another distribution with better support in the release cycle. Would you say that AppImage or another distribution channel receives better support? I like snaps because they're easy to (un)install, run in a semi-containerized environment, and auto-update with rollbacks, so they tend to be pretty reliable.

## Update

I tried installing using the tarball and AppImage, but they both complain about the glibc version on my machine. Snap gets around painful dependency issues like these 😭 I really don't want to upgrade glibc. It'll cause things to break.
```
(.venv) jalvarado@devrestricted-jalvarado:~/code/spinner-workflows$ nvim
/tmp/.mount_nvimDRSwjJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_nvimDRSwjJ/usr/bin/nvim)
/tmp/.mount_nvimDRSwjJ/usr/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_nvimDRSwjJ/usr/bin/nvim)
```

[1]: https://github.com/neovim/neovim/releases/tag/v0.10.0

**Comment by mlalkaka** [comment]
I ran into a similar challenge and wanted to continue using the Neovim snap. I've made a pull request (#30) that fixes the neovim-snap snapcraft.yaml file so that it works for the 0.10.0 release.

**Comment by justinmk** [comment]
> 've made a pull request (#30) that fixes the neovim-snap snapcraft.yaml file so that it works for the 0.10.0 release.

Thanks. I merged that. Now hoping that automation will do something, somewhere :)
