### ISSUE TITLE
Please update the stable to nvim 0.5.1

### ISSUE THREAD

**Issue by kush87** [neovim/neovim-snap#3]
The current stable release on snap is. 0.5.0-dirty.
However for some plugins to run properly, 0.5.1 is required(such as lunarvim).
So if you guys can update it to 0.5.1 that would be very helpful.

**Comment by hurricanehrndz** [comment]
This should have been done automatically by the build systems. I will try to do a manual push soon.

**Comment by kush87** [comment]
The edge seems to be reflecting the nightly builds currently but not the stable build.

**Comment by hurricanehrndz** [comment]
Yes well aware. The issues is that neovim no longer tags stable. Once I get a free moment I will address it. Pull request are also welcomed. The build scripts are all bash.

**Comment by hurricanehrndz** [comment]
@kush87 we have release 0.6.0

**Comment by kush87** [comment]
Thank you @hurricanehrndz . Greatly appreciate it.
