### ISSUE TITLE
Update stable snap to 0.10.1

### ISSUE THREAD

**Issue by mattgallagher92** [neovim/neovim-snap#31]
Thanks for maintaining a Neovim snap 🙂

Neovim [v0.10.1](https://github.com/neovim/neovim/releases/tag/v0.10.1) has been released, please could the snap be updated too?

Based on the fix in #30 and the comments in #23, #24, #26. I think this just requires somebody with permission to trigger a GitHub action? 🤷🏼

**Comment by justinmk** [comment]
@hurricanehrndz should we add a `workflow_dispatch` event trigger to the `Sync repo to Launchpad` workflow? Or what is the proper way to trigger that?

**Comment by hurricanehrndz** [comment]
I think all that needs to be done is edit the readme, and commit on the specific branch you wish to trigger a release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brianhuster** [comment]
After my pull request was accepted, Neovim-snap stable has been updated to 0.10.1, so I think this issue can be closed now
