### ISSUE TITLE
Update nightly version to the newest one (automate with GHA cron feature)

### ISSUE THREAD

**Issue by brianhuster** [neovim/neovim-snap#34]
Thanks for accepting my PR on the master branch, that has updated Neovim stable version to 0.10.1.

However, the nightly version isn't updated yet, it is still stuck at v0.11.0-v0.10.0+85+g93c55... which was updated on 25 May. So please accept my PR on the nightly branch to trigger Github Actions to update the nightly Snap package.

Thank you in advance

**Comment by justinmk** [comment]
I triggered the release manually using the `workflow_dispatch` trigger. Can someone send a PR to make this a cron job (using GHA's "cron" feature)?

**Comment by justinmk** [comment]
nightly will now trigger daily: https://github.com/neovim/neovim-snap/commit/5a21121154c60713a3e0e4c14e6f1e70792ec399

**Comment by justinmk** [comment]
I merged the `nightly` branch into `master`: https://github.com/neovim/neovim-snap/tree/master

Now `master` will produce both "stable" and "release" artifacts on a daily schedule.

And this means the `nightly` branch of this repo is no longer needed (it was confusing and weird anyway).

**Comment by justinmk** [comment]
working out some bugs 😂  ...

**Comment by justinmk** [comment]
> ~I merged the `nightly` branch into `master`: [e5d88e2](https://github.com/neovim/neovim-snap/commit/e5d88e2f2d3eb89ec9c93928889bb5427f1c71d6)~ Nevermind, snapcraft requires the separate branches 🤦

Documented how this repo works so I don't forget again :) 

https://github.com/neovim/neovim-snap?tab=readme-ov-file#how-this-repo-works

**Comment by justinmk** [comment]
@brianhuster this should be automated now. Please let me know if you notice the "edge" snap is not updating daily.

**Comment by brianhuster** [comment]
I will. Thank you for your hard work
