### ISSUE TITLE
Snap builds are failing

### ISSUE THREAD

**Issue by hurricanehrndz** [neovim/neovim-snap#37]
https://launchpadlibrarian.net/752497682/buildlog_snap_ubuntu_jammy_amd64_nvim-stable_BUILDING.txt.gz

**Comment by hurricanehrndz** [comment]
Ignore 
<img width="1956" alt="image" src="https://github.com/user-attachments/assets/6099614e-d322-4a66-b49e-3eb448cff20b">

**Comment by justinmk** [comment]
Thanks for the heads up!
