### ISSUE TITLE
Github Action "update-readme" doesn't automatically run daily on branch "nightly"

### ISSUE THREAD

**Issue by brianhuster** [neovim/neovim-snap#38]
If you check the branch "nightly", you will see that the file README hasn't been updated for 2 weeks (the last time was Oct 3). While in the branch "main", it does run daily. 

The strangest thing is that when I fork the branch "nightly" and manually trigger the action in that branch, it does work. So it just doesn't automatially run on schedule. I haven't found the reason yet, just let you know

**Comment by brianhuster** [comment]
OK, I have found the reason. [Github document](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule) says scheduled actions can **only** run on default branch, which is "master" branch in this repo

**Comment by justinmk** [comment]
Can we have the `master` CI job do a `git push` to the `nightly` branch?

**Comment by brianhuster** [comment]
I have made a pull request that add a new action "update-readme-nightly" to branch master. Please review it

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim-snap/pull/40

Thanks!
