### ISSUE TITLE
Can't open files using Nvim from terminal? It says: Permission denied

### ISSUE THREAD

**Issue by zhandosweb** [neovim/neovim-snap#42]
Hello! Please help me fix this issue.
I have installed the Snap version of Neovim 0.10.2
When I try to open any file or folder through the console (terminal), I get a "Permission denied" error.
![Image](https://github.com/user-attachments/assets/7cc0b215-55a2-423a-afcc-72f99aac9f36)

If I open Neovim from my home directory, I can navigate to the file path using Telescope (file explorer) and open the necessary file. However, I'm unable to open Neovim for specific folders/files directly. I think it might be related to the Snap package permissions.
Please help me fix this problem, I don't know what to do.

**Comment by zhandosweb** [comment]
Okay, close the issue and don't mind. I had to install it through Homebrew and everything works fine now!

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim-snap/issues/25#issuecomment-2391362362
