### ISSUE TITLE
Build type Debug instead of Release on Ubuntu Raspberry Pi  (arm64 architecture)

### ISSUE THREAD

**Issue by olbrew** [neovim/neovim-snap#9]
Even though the `snapcraft.yaml` defines [`CMAKE_BUILD_TYPE=RelWithDebInfo`](https://github.com/neovim/neovim-snap/blob/5fd77f3065793980b6e87e558efb9da0564cdad0/snap/snapcraft.yaml#L44) for the case of `arm64` architecture I get a debug build when installing `neovim` through a snap.

How can we change this to a Release buid?

### Steps to reproduce:
```fish
> sudo snap install nvim --classic
> nvim --version
NVIM v0.6.0
Build type: Debug
```

**Comment by hurricanehrndz** [comment]
Good question. This question would probably be better directed at snapcraft forums.

**Comment by hurricanehrndz** [comment]
Also have you tried changing the release to just Release.

**Comment by olbrew** [comment]
Do you mean to try rebuilding with `CMAKE_BUILD_TYPE` set to `Release` instead of `RelWithDebInfo`?

**Comment by olbrew** [comment]
I eventually switched to the Nix package so didn't look into it anymore.

**Comment by hurricanehrndz** [comment]
Yeah, and no worries.
